# Generated by Django 2.1.7 on 2019-04-01 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reaction',
            old_name='heart',
            new_name='hearts',
        ),
    ]
